# general 
threads: 36
output_path: "/scratch/indikar_root/indikar1/shared_data/fb_test/"

# input files
inputs:
    fastq_directory: "/nfs/turbo/umms-indikar/shared/projects/hybrid_reprogramming/data/fastq/biolegend_library/2025_01_23_Hybrid_TSB_Run1_L2"
    barcode_whitelist: "/nfs/turbo/umms-indikar/shared/projects/cell_cycle/data/10x_barcode_lists/3M-3pgex-may-2023.txt"

# read-length trimming
trim:
    min_length: 100
    max_length: 250